CREATE SCHEMA ESHOP;

CREATE TABLE ESHOP.USUARIO (
IdUsuario VARCHAR(10) PRIMARY KEY,
Password VARCHAR(40) NOT NULL,
Administrador CHAR NOT NULL,
Apellidos VARCHAR(56) NOT NULL,
Nombre VARCHAR(20) NOT NULL,
NIF CHAR(9) NOT NULL,
Direccion VARCHAR(200) NOT NULL,
Telefono VARCHAR(13) NOT NULL,
Email VARCHAR(40) NOT NULL,
Bonificado INT NOT NULL);

CREATE TABLE ESHOP.PEDIDO (
IdPedido VARCHAR(10) PRIMARY KEY,
NumCuenta CHAR(20) NOT NULL,
FechaPedido INT NOT NULL,
FCaducidad INT NOT NULL,
Direccion VARCHAR(200) NOT NULL,
Nombre_Cl VARCHAR(40) NOT NULL,
Estado VARCHAR(10) NOT NULL,
CIF_NIF CHAR(9) NOT NULL,
IdUsuario VARCHAR(10) NOT NULL,
FOREIGN KEY(IdUsuario) REFERENCES ESHOP.USUARIO(IdUsuario));

CREATE TABLE ESHOP.PRODUCTO (
IdProducto VARCHAR(10) PRIMARY KEY,
Agotado CHAR NOT NULL,
Ejemplares INT NOT NULL,
Puntuacion INT NOT NULL,
NumVotos INT NOT NULL,
PrecioUd INT NOT NULL,
Genero VARCHAR(40) NOT NULL,
Titulo VARCHAR(40) NOT NULL,
Fichero VARCHAR(100) NOT NULL,
Fecha INT NOT NULL,
Sinopsis VARCHAR(1000) NOT NULL);

CREATE TABLE ESHOP.PELICULA(
IdProducto VARCHAR(10) PRIMARY KEY,
Soporte CHAR(3) NOT NULL,
Director VARCHAR(40) NOT NULL,
Actores VARCHAR(200),
FOREIGN KEY(IdProducto) REFERENCES ESHOP.PRODUCTO(IdProducto));

CREATE TABLE ESHOP.VIDEOJUEGO(
IdProducto VARCHAR(10) PRIMARY KEY,
Plataforma VARCHAR(4) NOT NULL,
Companya VARCHAR(40) NOT NULL,
FOREIGN KEY(IdProducto) REFERENCES ESHOP.PRODUCTO(IdProducto));

CREATE TABLE ESHOP.PRODUCTOSPEDIDO (
IdPedido VARCHAR(10) NOT NULL,
IdProducto VARCHAR(10) NOT NULL,
Cantidad INT NOT NULL,
PRIMARY KEY(IdPedido,IdProducto),
FOREIGN KEY(IdPedido) REFERENCES ESHOP.PEDIDO(IdPedido),
FOREIGN KEY(IdProducto) REFERENCES ESHOP.PRODUCTO(IdProducto));

CREATE TABLE ESHOP.PUEDEVOTAR (
IdUsuario VARCHAR(10) NOT NULL,
IdProducto VARCHAR(10) NOT NULL,
Cantidad INT NOT NULL,
PRIMARY KEY(IdUsuario,IdProducto),
FOREIGN KEY(IdUsuario) REFERENCES ESHOP.USUARIO(IdUsuario),
FOREIGN KEY(IdProducto) REFERENCES ESHOP.PRODUCTO(IdProducto));