DROP TABLE ESHOP.PUEDEVOTAR;
DROP TABLE ESHOP.PRODUCTOSPEDIDO;
DROP TABLE ESHOP.VIDEOJUEGO;
DROP TABLE ESHOP.PELICULA;
DROP TABLE ESHOP.PRODUCTO;
DROP TABLE ESHOP.PEDIDO;
DROP TABLE ESHOP.USUARIO;

DROP SCHEMA ESHOP RESTRICT;